// Creator data — single source of truth

export const creators = [
  {
    id: 1,
    name: "Aria Nova",
    category: "Art & Illustration",
    subscribers: 2840,
    preview: "✦",
    avatar: "/creators/creator_1.jpg",
    tier: "from $5/mo",
    bio: {
      en: "Digital artist exploring the boundaries between light and shadow. Exclusive prints, process videos, and early access to new collections.",
      ko: "빛과 그림자의 경계를 탐구하는 디지털 아티스트. 독점 프린트, 과정 영상, 새 컬렉션 조기 접근.",
    },
    tiers: [
      { name: "Supporter", price: 5, perks: ["Monthly wallpaper pack", "Early access to new art"] },
      { name: "Collector", price: 15, perks: ["Everything in Supporter", "Monthly print (digital)", "Behind the scenes content"] },
      { name: "Patron", price: 30, perks: ["Everything in Collector", "1:1 monthly feedback session", "Name in credits"] },
    ],
    twitter: "@arianovo",
    instagram: "@aria.nova",
  },
  {
    id: 2,
    name: "Echo Veil",
    category: "Music & Audio",
    subscribers: 1520,
    preview: "♪",
    avatar: "/creators/creator_2.jpg",
    tier: "from $3/mo",
    bio: {
      en: "Ambient soundscapes and electronic compositions. New tracks every week, stems for download, and live listening sessions.",
      ko: "앰비언트 사운드스케이프와 전자음악 작곡. 매주 새 트랙, 스템 다운로드, 라이브 리스닝 세션.",
    },
    tiers: [
      { name: "Listener", price: 3, perks: ["Monthly exclusive track", "Early releases"] },
      { name: "Fan", price: 10, perks: ["Everything in Listener", "Stems & samples pack", "Monthly Q&A"] },
      { name: "Producer", price: 25, perks: ["Everything in Fan", "Full project files", "Collaboration opportunity"] },
    ],
    twitter: "@echoveil",
    instagram: "@echo.veil",
  },
  {
    id: 3,
    name: "Luna Craft",
    category: "Photography",
    subscribers: 4210,
    preview: "◈",
    avatar: "/creators/creator_3.jpg",
    tier: "from $8/mo",
    bio: {
      en: "Fine art photography from remote landscapes. Limited edition prints, location guides, and photography workshops.",
      ko: "오지 풍경을 담은 파인 아트 사진. 한정판 프린트, 위치 가이드, 사진 워크숍.",
    },
    tiers: [
      { name: "Explorer", price: 8, perks: ["Monthly photo essay", "Location notes"] },
      { name: "Adventurer", price: 20, perks: ["Everything in Explorer", "Full resolution downloads", "Editing presets"] },
      { name: "Expedition", price: 50, perks: ["Everything in Adventurer", "Monthly 1:1 mentorship", "Private workshop access"] },
    ],
    twitter: "@lunacraft",
    instagram: "@luna.craft",
  },
  {
    id: 4,
    name: "Nyx Studio",
    category: "Digital Art",
    subscribers: 3100,
    preview: "⬡",
    avatar: "/creators/creator_4.jpg",
    tier: "from $5/mo",
    bio: {
      en: "Concept art and world-building for games and films. Process breakdowns, asset packs, and design critiques.",
      ko: "게임과 영화를 위한 컨셉 아트와 세계관 구축. 과정 분석, 에셋 팩, 디자인 크리틱.",
    },
    tiers: [
      { name: "Viewer", price: 5, perks: ["Monthly asset pack", "Process videos"] },
      { name: "Student", price: 15, perks: ["Everything in Viewer", "Tutorial library access", "Brush packs"] },
      { name: "Artist", price: 35, perks: ["Everything in Student", "Monthly critique session", "Commission priority"] },
    ],
    twitter: "@nyxstudio",
    instagram: "@nyx.studio",
  },
  {
    id: 5,
    name: "Vex Origins",
    category: "Writing",
    subscribers: 980,
    preview: "✒",
    avatar: "/creators/creator_5.jpg",
    tier: "from $2/mo",
    bio: {
      en: "Dark fiction and world-building essays. Serialized stories, writing guides, and early manuscript access.",
      ko: "다크 픽션과 세계관 에세이. 연재 소설, 글쓰기 가이드, 원고 조기 접근.",
    },
    tiers: [
      { name: "Reader", price: 2, perks: ["Monthly short story", "Newsletter"] },
      { name: "Subscriber", price: 8, perks: ["Everything in Reader", "Full serialized novel access", "Writing notes"] },
      { name: "Collaborator", price: 20, perks: ["Everything in Subscriber", "Manuscript feedback", "Character naming rights"] },
    ],
    twitter: "@vexorigins",
    instagram: "@vex.origins",
  },
  {
    id: 6,
    name: "Sol Cipher",
    category: "Video & Film",
    subscribers: 2250,
    preview: "▶",
    avatar: "/creators/creator_6.jpg",
    tier: "from $10/mo",
    bio: {
      en: "Independent filmmaker and visual storyteller. Short films, director commentary, and filmmaking masterclasses.",
      ko: "독립 영화감독이자 비주얼 스토리텔러. 단편 영화, 감독 코멘터리, 영화 제작 마스터클래스.",
    },
    tiers: [
      { name: "Watcher", price: 10, perks: ["Monthly short film", "Director commentary"] },
      { name: "Cinephile", price: 25, perks: ["Everything in Watcher", "Extended cuts", "Script access"] },
      { name: "Producer", price: 60, perks: ["Everything in Cinephile", "Set visit (virtual)", "Executive producer credit"] },
    ],
    twitter: "@solcipher",
    instagram: "@sol.cipher",
  },
  {
    id: 7,
    name: "Dusk Atelier",
    category: "Art & Illustration",
    subscribers: 1890,
    preview: "◐",
    avatar: "/creators/creator_7.jpg",
    tier: "from $6/mo",
    bio: {
      en: "Surrealist illustrations and limited edition prints.",
      ko: "초현실주의 일러스트와 한정판 프린트.",
    },
    tiers: [
      { name: "Admirer", price: 6, perks: ["Monthly illustration", "Early access"] },
      { name: "Collector", price: 18, perks: ["Everything in Admirer", "Print downloads", "Process videos"] },
      { name: "Patron", price: 40, perks: ["Everything in Collector", "Signed prints", "Studio visits"] },
    ],
    twitter: "@duskatelier",
    instagram: "@dusk.atelier",
  },
  {
    id: 8,
    name: "Vera Sine",
    category: "Music & Audio",
    subscribers: 3400,
    preview: "♫",
    avatar: "/creators/creator_8.jpg",
    tier: "from $4/mo",
    bio: {
      en: "Classical piano meets modern electronic production.",
      ko: "클래식 피아노와 현대 전자음악의 만남.",
    },
    tiers: [
      { name: "Listener", price: 4, perks: ["Monthly track", "Sheet music"] },
      { name: "Student", price: 12, perks: ["Everything in Listener", "Tutorial videos", "MIDI files"] },
      { name: "Collaborator", price: 30, perks: ["Everything in Student", "1:1 lessons", "Remix rights"] },
    ],
    twitter: "@verasine",
    instagram: "@vera.sine",
  },
  {
    id: 9,
    name: "Frost Frame",
    category: "Photography",
    subscribers: 2100,
    preview: "❄",
    avatar: "/creators/creator_9.jpg",
    tier: "from $7/mo",
    bio: {
      en: "Arctic and wilderness photography.",
      ko: "북극과 야생 사진.",
    },
    tiers: [
      { name: "Explorer", price: 7, perks: ["Monthly photo series", "Location guides"] },
      { name: "Adventurer", price: 20, perks: ["Everything in Explorer", "Raw files", "Editing presets"] },
      { name: "Expedition", price: 45, perks: ["Everything in Adventurer", "Workshop access", "Print collection"] },
    ],
    twitter: "@frostframe",
    instagram: "@frost.frame",
  },
];

export type Creator = typeof creators[0];
